name: 'Build Godot Project'
description: 'Builds a Godot project for multiple platforms and creates a GitHub release with the exported builds attached.'


inputs:
  godot_project_name:
    description: 'Name of the project'
    required: true
    default: 'GodotProject'
  upload_release:
    description: 'Create new Release'
    required: true
    default: 'false'
  godot_build_config:
    description: 'Create new Release'
    required: true
    default: 'Linux'
  github_token:
    description: 'Create new Release'
    required: true
    default: 'Linux'

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build 
      id: build_godot
      uses: bbrieber/godot_ci_image@5b1371c10215a38f5b897180656a8f7d05624ebd
      with:
        build-config: ${{ inputs.godot_build_config }}
    - name: Zip Folder
      id: zip_folder
      shell: bash
      run: |
        cd export/${{ inputs.godot_build_config }}
        zip -r ${{ inputs.godot_project_name }}_${{ inputs.godot_build_config }}.zip .
        cd ../..
    - name: Create Release
      id: create_release
      if: ${{ inputs.upload_release }}
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
    - name: Upload Release Asset Linux
      id: upload-release-asset-linux
      if: ${{ inputs.upload_release }}
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: export/${{ inputs.godot_build_config }}/${{ inputs.godot_project_name }}_${{ inputs.godot_build_config }}.zip
        asset_name: ${{ inputs.godot_project_name }}_${{ inputs.godot_build_config }}-${{ github.ref_name }}.zip
        asset_content_type: application/zip
